export interface Podcast {
  id: number,
  title: string,
  url: string,
  originalUrl: string,
  link: string,
  description: string,
  author: string,
  ownerName: string,
  image: string,
  artwork: string,
  lastUpdateTime: number,
  lastCrawlTime: number,
  lastParse: string,
  inPollingQueue: number,
  priority:number,
  lastGoodHttpStatusTime: number,
  lastHttpStatus: number,
  contentType: string,
  itunesId: number,
  generator: string,
  language: string,
  type: number,
  dead: number,
  crawlErrors: number,
  parseErrors: number,
  categories: {
    [key: string]: string
  },
  locked: number,
  explicit: boolean,
  podcastGuid: string,
  medium: string,
  episodeCount: number,
  imageUrlHash: number,
  newestItemPubdate: number
}