export interface Podcast {
  public id: number,
  public title: string,
  public url: string,
  public originalUrl: string,
  public link: string,
  public description: string,
  public author: string,
  public ownerName: string,
  public image: string,
  public artwork: string,
  public lastUpdateTime: number,
  public lastCrawlTime: number,
  public lastParse: string,
  public inPollingQueue: number,
  public priority:number,
  public lastGoodHttpStatusTime: number,
  public lastHttpStatus: number,
  public contentType: string,
  public itunesId: number,
  public generator: string,
  public language: string,
  public type: number,
  public dead: number,
  public crawlErrors: number,
  public parseErrors: number,
  public categories: {
    [key: string]: string
  },
  public locked: number,
  public explicit: boolean,
  public podcastGuid: string,
  public medium: string,
  public episodeCount: number,
  public imageUrlHash: number,
  public newestItemPubdate: number
}